version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      go:
        patterns:
          - '*'
    commit-message:
      prefix: Dependabot
