# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1
builds:
  - main: ./cmd/ejsonkms
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
    ignore:
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: ppc64le
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
